<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Buy Now'); ?>
<?php if ($_product->isSaleable()):?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()):?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $escaper->escapeHtml(__('Add Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                        name="qty"
                        id="qty"
                        min="0"
                        value="<?= $block->getProductDefaultQty() * 1 ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                        class="input-text qty"
                        data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        /><br><br>
                <span class="product-social-links">
                    <span class="product-addto-links" data-role="add-to-links">
                        <?= $block->getBlockHtml('custom.addto.wishlist') ?>
                        <?= $block->getBlockHtml('custom.addto.compare') ?>
                    </span>
                </span>
                
            </div>
        </div>
        

        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
            </button>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
